%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\user_bortolozzi\Documents\DATA\analisisMEA\20220324_Assem-NHDF-chip_SpikeList_Plate01_004DIV_xxxDIV_xxxDIV(decrypted).csv
%
% Auto-generated by MATLAB on 16-Aug-2023 15:57:22
function  spiketable=importingCSV_SpikeList(file)
%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, 5048576];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Times", "Electrode", "AmplitudemV"];
opts.SelectedVariableNames = ["Times", "Electrode", "AmplitudemV"];
opts.VariableTypes = ["char", "char", "double", "char", "double"];
opts = setvaropts(opts, [1, 2, 4], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 4], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
spiketable = readtable(file, opts);


%% Clear temporary variables
clear opts
end